justinmk/vim-dirvish

- autoload/dirvish.vim
- plugin/dirvish.vim
No need to redefine `<Plug>` mappings every time you open a `dirvish` buffer.
> Move mappings to the plugin file. Also some code cleanup.

- ftplugin/dirvish.vim
I cannot move to the parent directory using '-' without this fix in Vim version 7.4.922
> change nmap -> nnoremap for moving to parent dir

- autoload/dirvish.vim
Just a small nitpick. I think you simply forgot the `:silent` in this line, since you use it for the same purpose 2 lines above it already.
> [RFC] Silence :delete

- autoload/dirvish.vim
e55329a3fc1bb546098e37f77eb8e4e0d1edda15 break on windows
> Fix wildcard on Windows

- ftplugin/dirvish.vim
- plugin/dirvish.vim
This adds `<Plug>(dirvish_split_up)` and `<Plug>(dirvish_vsplit_up)`
which act like `<Plug>(dirvish_up)` after splitting the window.
> Add <Plug> nmaps for split windows

- autoload/dirvish.vim
If a modified buffer has multiple windows, nothing will be lost when
navigating away from it with dirvish.  We can figure out how many there
are with `win_findbuf`.  (Worst case, if this is ever done wrong, Vim
will still raise the error itself.)
Fixes #47
> Don't error leaving modified buffers with multiple windows

- autoload/dirvish.vim
With 'noautoread' Vim will notify you about the file being changed.
> Warning: Mode of file "{filename}" has changed since editing started
We could only do this with `!&noautoread`?!
> Shmod: execute edit after chmod to avoid W16

- ftplugin/dirvish.vim
Currently, when R is pressed without a count, `:|Dirvish %` gets executed. This results in the current line being echoed because of the `:|` command.
> Only add a <Bar> when a count is given

- autoload/dirvish.vim
Commit e1548de9dcfe3 make Z! exe empty string instead of '%' on windows.
> Fix Z! on windows again

- doc/dirvish.txt
Use case:
* delete a line in file A
* navigate to a file B using dirvish (with dotfiles hidden)
* try to paste the line in B
→ dotfiles are pasted instead
So, use `:normal "_dd` in automatic commands to send the lines to the black hole register.
> doc: preserve registers when hiding dot files

- plugin/dirvish.vim
Don't rely on compatability behaviour.
---
I'm not sure if there was a time where `version` did exist and `v:version` did not, but if so, it was pre-7.0 (~13 years).
Maybe checking for `v:version < 700` should be removed entirely. :>
> version -> v:version

- autoload/dirvish.vim
```
If you would enter a directory and go back multiple times, both dirvish buffers
would set the same autocmds multiple times.
```
> s:buf_init(): don't set autocmds multiple times

- autoload/dirvish.vim
- ftplugin/dirvish.vim
Here's a neat example given in the README of the project:
git ls-files | vim +'setf dirvish' -
It works well, except for the `q` and `x` buffer-local mappings.
They don't work immediately because their `rhs` are `<plug>` mappings, which are are not defined in a `plugin/` directory, but in an `autoload/` one.
Consider this minimal `vimrc` written in `/tmp/vimrc`:
set rtp^=~/.vim/plugged/vim-dirvish/
set rtp+=~/.vim/plugged/vim-dirvish/after
filetype plugin indent on
From the directory of `vim-dirvish`, if I start Vim like this:
$ git ls-files | vim -Nu /tmp/vimrc +'setf dirvish' -
Vim opens a dirvish buffer listing the contents of the directory.
But if I press `x` on a filepath to add it to the arglist, nothing happens.
This PR tries to fix the issue by moving the `<plug>` mappings in the …
> `x` and `q` don't work with `$ git ls-files | vim +'setf dirvish' -`

- autoload/dirvish.vim
This is a trivial fix to avoid complaining and aborting on unsaved changes when `autowriteall` is set, since the changes will be saved automatically.
> Don't signal E37 when 'autowriteall' is set

- autoload/dirvish.vim
The PR is mainly aimed at users who want to generate and execute a bash script (`.sh`) on Windows OS, provided they have `&shell` set to `sh.exe`. This allows users to use `:[range]Shdo[!] {cmd}` with basic unix commands such as `mv`, `rm`, etc.; as well as avoiding a need to `set shellslash` which oftentimes breaks other plugins (e.g. `vim-fugitive`).
As for non `git-bash` users on Windows OS, the original workflow is preserved i.e. a batch (`.bat`) or powershell (`.ps1`) script will be generated and executed instead via `cmd.exe` or `powershell.exe`, respectively.
For example, to rename a list of visual-selected files on Windows OS:
```
:'<,'>Shdo mv {} {}
%TEMP%\XXXXXXX.tmp.sh
Z!
```
```
:'<,'>Shdo ren {} {}
%TEMP%\XXXXXXX.tmp.bat
Z!
```
```
:'<,'>Shdo rename-item {} {} …
```
> Shdo: Z!: Added compatibility with `git-bash` on Windows OS

- autoload/dirvish.vim
`s:apply_icons` determines the path is a directory or not by `f[-1:] == '/'`. On Windows, path separator is not '/' but '\\'. So icons are not shown for directories on Windows.
> Fix icons do not work with directories on Windows

- autoload/dirvish.vim
Sometimes, the height of the window where `:Dirvish` is run changes:
$ vim -Nu <(echo 'set wmh=0 rtp^=~/.vim/plugged/vim-dirvish') +'sp|wincmd _'
:Dirvish
Notice how the height of the current window has decreased by 1, and how 1 line of the previous window is now visible while there was none before.
---
The issue comes from these lines:
https://github.com/justinmk/vim-dirvish/blob/fa6197150dbffe0f93028c46cd229bcca83105a9/autoload/dirvish.vim#L327
https://github.com/justinmk/vim-dirvish/blob/fa6197150dbffe0f93028c46cd229bcca83105a9/autoload/dirvish.vim#L333
They temporarily focus a different window, which may have the side-effect of changing the height of the current one. This only happens if you set `'winminheight'` to 0, in which case a non-focused window can be squashed to 0 lines. The …
> preserve window height when 'winminheight' is 0

- autoload/dirvish.vim
I'm sorry but the PR #149 I sent did not fix the reported issue entirely.
Here is another case where the height of the window is not preserved:
$ vim -Nu <(cat <<'EOF'
set wmh=0
set rtp^=~/.vim/plugged/vim-dirvish
au VimEnter * call Set_layout()
fu Set_layout()
bo sp
helpg foobar
close|copen
wincmd p|1wincmd w|2wincmd w
wincmd _
call win_execute(win_getid(3), 'resize 10')
endfu
EOF
)
From this layout, if `:Dirvish` is run, the height of the window decreases by `1`.
The issue disappears if `1wincmd w|2wincmd w` is removed; its purpose is to set the previous window. So I guess that the issue lies somewhere in the dirvish code which tries to preserve the number of the previous window.
It may seem as a contrived example, but I found it in a real usage scenario (using a plugin which …
> preserve window height when 'winminheight' is 0 (follow-up)

- plugin/dirvish.vim
fix #160 
I didn't care about compability about old fugitive because FugitiveDetect() exists since 2 years ago
https://github.com/tpope/vim-fugitive/blame/b129752c07eea803356e77d263aedbd17cd19acd/plugin/fugitive.vim#L272
> change legacy api: "fugitive#detect" to "FugitiveDetect"

- autoload/dirvish.vim
This PR tries to fix an issue where `E95` is raised when viewing a directory matching the CWD, and a hidden terminal buffer exists, as discussed in the issue #168.
> fix E95 when viewing directory matching CWD

- autoload/dirvish.vim
This PR prevents dirvish from translating backslashes into slashes outside Windows, to let the user open a file path containing a literal backslash.  This should fix the issue #173.
> Don't normalize slashes outside Windows

- autoload/dirvish.vim
If an autocmd changes the current window on FileType, it could raise unexpected errors.  Giving a warning could help the user to fix them.  Should fix issue #158.
> Warn the user about autocmd changing the window on FileType

- syntax/dirvish.vim
For windows backslash should be escaped in [^\].
Fixes #192
> fix: Pattern delimiter not found

- autoload/dirvish.vim
Fix dirvish for auto-mounted paths where mount root does not glob.
Problem: vim `glob()` does not match in subdirectories of some auto mounted paths, for example,
in `/home/autouser/docs/`.  This is probably because `autouser` does not glob in `/home/`.
Solution: use `globpath` instead of `glob` to do glob expansion only in leaf directory.
> Get directory listing with globpath

- plugin/dirvish.vim
On Windows,
When the dirvish buffer for a directory does not exist yet,
an empty string is passed to `s:isdir` and as a result, the dirvish buffer is empty and it is necessary to type `-` from that buffer to get the expected buffer content.
I noticed that using full paths instead of a relative path addressed the issue.
> use full path instead of relative path when opening a directory

- autoload/dirvish.vim
Fixes #183 
I confirmed this fix with the following steps:
1. Open Vim or Neovim
2. `:e file-a.txt`
3. `:e file-b.txt`
4. `:Dirvish`
5. Type `gq`
6. Type `<C-^>`
7. Confirm the current buffer was switched to file-a.txt
> Do not update alternate buffer on opening directory

- autoload/dirvish.vim
Some plugins need `autocmd`, for example, [vim-airline's dirvish extension](https://github.com/vim-airline/vim-airline/blob/master/autoload/airline/extensions/dirvish.vim#L25) may report error: `Undefined variable: b:dirvish`
> fix buf_close() noau

- autoload/dirvish.vim
`globpath()` may return a List after v7.4.279.
> Fix version check for globpath()

- ftplugin/dirvish.vim
**Problem:** The Dirvish key mappings that are `<silent>` prevent Vim from asking the user to enter an encryption key when an encrypted file is opened from Dirvish (`:help encryption`).
**Solution:** Remove `<silent>` from the key mappings that call `dirvish#open()` and replace `:call` with `<cmd>call`.
> Bug fix: The key mappings that are <silent> prevent Vim from asking the user to enter an encryption key

- autoload/dirvish.vim
Version: Neovim v0.9.4 and Vim 9.0 running on Linux and Windows
I am a long-time dirvish user, but only recently started using the dirvish#add_icon_fn() to add devicons to the dirvish display.  However, I found that occasionally the filenames displayed by dirvish are truncated from the left when the icons are being applied.
To see the issue, create files 'abc-file.txt', 'defg-file.txt', and 'file.txt' in a directory and display them in a dirvish buffer.  All filenames display as 'file.txt' as shown below.
This Neovim screenshot was taken on a Windows workstation, but the same behavior can be seen in Neovim and Vim on both Linux and Windows machines.
The problem seems to occur when the base name of one of the files in the directory matches the right-hand portion of one or more other …
> fix(apply_icons): filename may be truncated

- README.md
- autoload/dirvish.vim
- doc/dirvish.txt
This PR doesn't change much, it just make the function `s:apply_icons()` global by changing its name `dirvish#apply_icons()`. This allows users to have better control about when icons should be applied.
An example usage of this PR is [vim-dirvish-git.lua](https://github.com/brianhuster/vim-dirvish-git.lua)
Related to [#246]
> docs: more extensions
